<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130191025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE unit_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assignment VARCHAR(255) NOT NULL, scope VARCHAR(255) NOT NULL, unit_id INT NOT NULL, servant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_336DD27AF8BD700D ON unit_assignment (unit_id)');
        $this->addSql('CREATE INDEX IDX_336DD27A113ADFC0 ON unit_assignment (servant_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, servant_id INT DEFAULT NULL, team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649113ADFC0 ON "user" (servant_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649296CD8AE ON "user" (team_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE unit_assignment ADD CONSTRAINT FK_336DD27AF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unit_assignment ADD CONSTRAINT FK_336DD27A113ADFC0 FOREIGN KEY (servant_id) REFERENCES servant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649113ADFC0 FOREIGN KEY (servant_id) REFERENCES servant (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE unit_assignment DROP CONSTRAINT FK_336DD27AF8BD700D');
        $this->addSql('ALTER TABLE unit_assignment DROP CONSTRAINT FK_336DD27A113ADFC0');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649113ADFC0');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649296CD8AE');
        $this->addSql('DROP TABLE unit_assignment');
        $this->addSql('DROP TABLE "user"');
    }
}
