<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260128215142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subfondo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE unit ADD is_generating BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE unit ADD team_id INT NOT NULL');
        $this->addSql('ALTER TABLE unit ADD subfondo_id INT NOT NULL');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53A1C1B300 FOREIGN KEY (subfondo_id) REFERENCES subfondo (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_DCBB0C53296CD8AE ON unit (team_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C53A1C1B300 ON unit (subfondo_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE subfondo');
        $this->addSql('DROP TABLE team');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53296CD8AE');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53A1C1B300');
        $this->addSql('DROP INDEX IDX_DCBB0C53296CD8AE');
        $this->addSql('DROP INDEX IDX_DCBB0C53A1C1B300');
        $this->addSql('ALTER TABLE unit DROP is_generating');
        $this->addSql('ALTER TABLE unit DROP team_id');
        $this->addSql('ALTER TABLE unit DROP subfondo_id');
    }
}
